Adding Update and Delete Mentors API
UCF-ELLE/ELLE-Website-API pull request #7
Opened 2023-01-20 02:54 UTC by Keilvin

2023-01-20 14:01 UTC, Naton-1 approved these changes

2023-01-20 16:29 UTC, JustinRMoy requested changes
I made 3 comments on things that need to be changed before we merge. 1 is critical as it will just result in an error that being the import statements for the api

2023-01-20 16:29 UTC, JustinRMoy commented on utils.py
> +    query = "UPDATE `question` SET `question` = %s WHERE `questionID` = %s"
the ` around question and questionID are unnecessary.

2023-01-20 16:29 UTC, JustinRMoy commented on resources/mentors.py
> +                    log_query = "UPDATE `logged_answer` SET `questionID` = %s, `deleted_questionID` = %s WHERE `logID` = %s"
we're not using logged_answer. The student answers to mentor questions go to the mentor_responses table

2023-01-20 16:29 UTC, JustinRMoy commented on __init__.py
> +api.add_resource(DeleteMentorQuestion, API_ENDPOINT_PREFIX + 'deletementorquestions')
You need to import the classes for these two API endpoints at line 33

2023-01-23 17:40 UTC, Keilvin commented on resources/mentors.py
> +                    log_query = "UPDATE `logged_answer` SET `questionID` = %s, `deleted_questionID` = %s WHERE `logID` = %s"
logged answer does not in fact log the answers, log answer logs the session statistics and the log time as well as when the questions are added and deleted. In this case it updates the log of this particular questionID to be a deleted question.

2023-01-24 04:05 UTC, JustinRMoy approved these changes

2023-01-24 04:29 UTC, merged